# Generated by Django 5.2.3 on 2025-11-01 12:44

import django.db.models.deletion
import dokans.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='trial_end',
            field=models.DateField(default=dokans.models.Store.get_trial_end),
        ),
    ]
